import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { _electron as electron } from 'playwright';
import { createHarness, waitForTask } from './api-harness.js';

const h = await createHarness();
await h.stop();
const executablePath = process.env.INKTIME_APP_PATH || path.resolve('release/mac-arm64/InkTime Gallery.app/Contents/MacOS/InkTime Gallery');
let desktop;
const env = { ...process.env, INKTIME_USER_DATA_DIR:path.join(h.root,'desktop'), INKTIME_CONFIG_DIR:path.join(h.root,'config'), INKTIME_DATA_ROOT:path.join(h.root,'data'), INKTIME_PORT:new URL(h.url).port, INKTIME_DISABLE_SYSTEM_INTEGRATION:'1' };
const launch = () => electron.launch({ executablePath, env, timeout:45000 });
try {
  const started=performance.now();
  desktop = await launch();
  const window = await desktop.firstWindow();
  await window.getByRole('heading',{name:'照片管理',exact:true}).waitFor();
  const bootMs=performance.now()-started;
  const log=await fs.readFile(path.join(h.root,'desktop','logs','main.log'),'utf8');
  const lines=log.trim().split('\n').map(line => { const match=line.match(/^\[([^\]]+)\] (.*)$/); return match ? {at:Date.parse(match[1]),message:match[2]} : null; }).filter(Boolean);
  const origin=lines[0].at;
  const startupSteps=lines.filter(line => /boot packaged|electron ready|runtime config|server imported|main window created/.test(line.message)).map(line => ({step:line.message.split(/[ =]/).slice(0,2).join(' '),elapsedMs:line.at-origin}));
  const created=await h.request('/api/process','POST',{mode:'new'});
  assert.equal(created.status,202);
  await desktop.evaluate(({BrowserWindow}) => BrowserWindow.getAllWindows()[0].close());
  assert.equal(await desktop.evaluate(({BrowserWindow}) => BrowserWindow.getAllWindows()[0].isVisible()),false);
  assert.equal((await waitForTask(h,created.data.taskId)).succeeded,1);
  const photo=(await h.request('/api/photos?collection=all')).data.items[0];
  assert.equal((await fetch(h.url+photo.renderedUrl)).status,200);
  h.setDelay(2000);
  const rerun=await h.request('/api/process','POST',{sourceIds:[photo.sourceId],mode:'rerun'});
  await new Promise(resolve => setTimeout(resolve,100));
  await desktop.close();
  desktop=null;
  h.setDelay(0);
  desktop=await launch();
  await (await desktop.firstWindow()).getByRole('button',{name:/照片管理/}).waitFor();
  const recovered=(await h.request('/api/tasks/'+rerun.data.taskId)).data;
  assert.equal(recovered.status,'paused');
  await h.request('/api/tasks/'+rerun.data.taskId+'/resume','POST');
  assert.equal((await waitForTask(h,rerun.data.taskId)).succeeded,1);
  await desktop.close();
  desktop=null;
  const calls=h.calls;
  await promisify(execFile)(executablePath,['--wallpaper-once'],{env,timeout:20000});
  assert.equal(h.calls,calls,'One-shot wallpaper must not start AI');
  await assert.rejects(fetch(h.url+'/api/config'));
  const result={noWindowOneShot:true,bootMs,startupSteps,packaged:true,closeContinues:true,quitPauses:true,restartResumes:true,realRender:true};
  await fs.mkdir('tmp/upgrade',{recursive:true});
  await fs.writeFile('tmp/upgrade/desktop-metrics.json',JSON.stringify(result,null,2));
  console.log(JSON.stringify(result,null,2));
} finally { if(desktop) await desktop.close(); await h.close(); }
